services:
  mysql:
    image: mysql:8.0
    container_name: afms_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-strongpassword123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-afms_db}
      MYSQL_USER: ${MYSQL_USER:-afms_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-strongpassword123}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - afms_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: afms_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - afms_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  laravel-api:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      args:
        - APP_ENV=production
    container_name: afms_laravel_api
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME:-AFMS}
      - APP_ENV=${APP_ENV:-production}
      - APP_KEY=${APP_KEY:-base64:your_laravel_app_key_here}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${APP_URL:-https://cvtigaputraperkasa.id}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-afms_db}
      - DB_USERNAME=${DB_USERNAME:-afms_user}
      - DB_PASSWORD=${DB_PASSWORD:-strongpassword123}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SESSION_DOMAIN=${SESSION_DOMAIN:-.cvtigaputraperkasa.id}
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS:-cvtigaputraperkasa.id,www.cvtigaputraperkasa.id}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://cvtigaputraperkasa.id,https://www.cvtigaputraperkasa.id}
      - CORS_SUPPORTS_CREDENTIALS=true
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/storage:/var/www/html/storage
      - ./laravel/bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - afms_network

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: afms_nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://cvtigaputraperkasa.id/api}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL:-https://cvtigaputraperkasa.id}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-key-here}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://cvtigaputraperkasa.id}
    ports:
      - "3000:3000"
    depends_on:
      - laravel-api
    networks:
      - afms_network

networks:
  afms_network:
    driver: bridge

volumes:
  mysql_data: